#!/bin/bash 

#SBATCH -J CSDE1_kallisto_ENSEMBL
#SBATCH --mem=100G
#SBATCH -N 1 
#SBATCH -n 1 
#SBATCH -t 05:00:00
#SBATCH -c 16


#ASSIGN TOOLS
kallisto=/work/yang_lab/reza/tools/kallisto/kallisto
input=/work/yang_lab/2_Raw_data_yanglab/220601_NB501138_0313_AHLM7LBGXL_Csde1-RIP/Data/*
output=/work/yang_lab/queenie/csde1_RIP/kallisto_ENSEMBL/
reference=/work/yang_lab/queenie/ENSEMBL_GRCm39_cds/Mus_musculus.GRCm39.cds.all.fa

# Run
i=0

for FILE in $input*fastq 
do echo "trials starting for"
echo $i
echo "Accessing this file"
echo $FILE

$kallisto quant -i $reference -o $output$i".kallisto" --single -l 181 -s 20 --bias -b 100 -t 40 $FILE

echo "trial" $i "complete"
((i++))
echo "-------------"
done
done
